name: Build and deploy Docuchain backend

on:
  push:
    branches: [ "main", "cicd" ]
  workflow_dispatch:

jobs:

  deploy:

    runs-on: [ "self-hosted", "prod" ]

    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Build docker image
      run: make build-prod

    - name: Start application
      run: source /home/deployer/ansible/bin/activate && cd ansible && ansible-playbook deploy-backend.yml -e ansible_user=deployer -b -v
      env:
        DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        GCS_PROJECT_ID: ${{ secrets.GCS_PROJECT_ID }}
        GCS_PRIVATE_KEY_ID: ${{ secrets.GCS_PRIVATE_KEY_ID }}
        GCS_PRIVATE_KEY: ${{ secrets.GCS_PRIVATE_KEY }}
        GCS_CLIENT_EMAIL: ${{ secrets.GCS_CLIENT_EMAIL}}
        GCS_CLIENT_ID: ${{ secrets.GCS_CLIENT_ID }}
        GOOGLE_SECRET: ${{ secrets.GOOGLE_SECRET }}
        GCS_CLIENT_X509_CERT_URL: ${{ secrets.GCS_CLIENT_X509_CERT_URL }}
        GCS_BUCKET_NAME: ${{ secrets.GCS_BUCKET_NAME }}
        MANDRILL_API_KEY: ${{ secrets.MANDRILL_API_KEY }}
        MANDRILL_WEBHOOK_KEY: ${{ secrets.MANDRILL_WEBHOOK_KEY }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        MATIC_PRIVATE_KEY: ${{ secrets.MATIC_PRIVATE_KEY }}
        POLYGON_RPC_NODE: ${{ secrets.POLYGON_RPC_NODE }}
        BSC_RPC_NODE: ${{ secrets.BSC_RPC_NODE }}
        BSC_RPC_NODE_ANC: ${{ secrets.BSC_RPC_NODE_ANC }}
        BSC_RPC_NODE_DEFI: ${{ secrets.BSC_RPC_NODE_DEFI }}
        BSC_PRIVATE_KEY: ${{ secrets.BSC_PRIVATE_KEY }}
        SOLANA_RPC_NODE: ${{ secrets.SOLANA_RPC_NODE }}
        SOLANA_RPC_NODE_ANC: ${{ secrets.SOLANA_RPC_NODE_ANC }}
        SOLANA_PRIVATE_KEY: ${{ secrets.SOLANA_PRIVATE_KEY }}
        SOLANA_CLUSTER: ${{ secrets.SOLANA_CLUSTER }}
        MONAD_PRIVATE_KEY: ${{ secrets.MONAD_PRIVATE_KEY }}
        MONAD_RPC_NODE: ${{ secrets.MONAD_RPC_NODE }}
        MONAD_RPC_NODE_ANC: ${{ secrets.MONAD_RPC_NODE_ANC }}
        BASE_PRIVATE_KEY: ${{ secrets.BASE_PRIVATE_KEY }}
        BASE_RPC_NODE: ${{ secrets.BASE_RPC_NODE }}
        BASE_RPC_NODE_ANC: ${{ secrets.BASE_RPC_NODE_ANC }}
        BASE_RPC_NODE_DRPC: ${{ secrets.BASE_RPC_NODE_DRPC }}
        BITCOIN_PRIVATE_KEY: ${{ secrets.BITCOIN_PRIVATE_KEY }}
        BITCOIN_RPC_NODE: ${{ secrets.BITCOIN_RPC_NODE }}
        BITCOIN_RPC_NODE_2: ${{ secrets.BITCOIN_RPC_NODE_2 }}
        BITCOIN_RPC_NODE_MEMPOOL: ${{ secrets.BITCOIN_RPC_NODE_MEMPOOL }}
        BITCOIN_NETWORK: ${{ secrets.BITCOIN_NETWORK }}
        BITCOIN_FEE_RATE: ${{ secrets.BITCOIN_FEE_RATE }}
        SEI_PRIVATE_KEY: ${{ secrets.SEI_PRIVATE_KEY }}
        SEI_RPC_NODE: ${{ secrets.SEI_RPC_NODE }}
        SEI_RPC_NODE_2: ${{ secrets.SEI_RPC_NODE_2 }}
        SEI_RPC_NODE_3: ${{ secrets.SEI_RPC_NODE_3 }}
        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        WALLET_ALERT_TG_BOT_TOKEN: ${{ secrets.WALLET_ALERT_TG_BOT_TOKEN }}
        WALLET_ALERT_TG_CHAT_ID: ${{ secrets.WALLET_ALERT_TG_CHAT_ID }}
